config/routes.rb
Polo::Application.routes.draw do
  root 'homes#index'

  get '/roster', to: 'players#roster'
  get '/coaching_staff', to: 'coaches#coaching_staff'
  get '/schedule', to: 'tournaments#schedule'
  get '/photos', to: 'static#photos'
  get '/files', to: 'resources#files'


  get '/admin', to: 'players#index'

  scope :admin do
    resources :teams, except: [:show]
    resources :players, except: [:show]
    resources :coaches, except: [:show]
    resources :tournaments
    resources :games, except: [:show]
    resources :resources, except: [:show]
  end
end

app/models/coach.rb
class Coach < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name ,presence: true
  validates :email ,presence: true
  validates :title ,presence: true
  validates :bio ,presence: true
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :tournament
  belongs_to :team

  def ha
    if self.home
      "Home"
    else
      "Away"
    end
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team

  validates :first_name, presence: true
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  validates :filename, uniqueness: true
  validates :name, uniqueness: true
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :players
  has_many :games

  validates :name, presence: true
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  has_many :games, ->  { order("date ASC, time ASC") }

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  layout "admin", except: [:coaching_staff]

  before_action :set_coach, only: [:edit, :update, :destroy]

  def index
    @coaches = Coach.all
  end

  def coaching_staff
    @coaches = Coach.all
  end

  def new
    @coach = Coach.new
  end 

  def create
    @coach = Coach.new(coach_params)

    if @coach.save
      flash[:notice] = "The coach was created"
      redirect_to coaches_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @coach.update(coach_params)
      flash[:notice] = "The coach was updated"
      redirect_to coaches_path
    else
      render :edit
    end
  end

  def destroy
    @coach.destroy
    redirect_to coaches_path
  end

  private

  def set_coach
    @coach = Coach.find(params[:id])
  end

  def coach_params
    params.require(:coach).permit(:first_name, :last_name, :title, :email, :bio)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  layout "admin"

  def index
    @games = Game.all
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)

    if @game.save
      flash[:notice] = "The game was created"
      redirect_to games_path
    else
      render :new
    end
  end

  private

  def game_params
    params.require(:game).permit(:tournament_id, :pool, :team_id, :opponent, :date, :time, :home)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  layout "admin", except: [:roster]

  def index
    @teams = Team.all
    @unassigned_players = Player.where(team_id: nil)
  end

  def roster
    @teams = Team.all
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)

    if @player.save
      flash[:notice] = "Player created."
      redirect_to players_path
    else
      render :new
    end
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])

    if @player.update(player_params)
      flash[:notice] = "Player updated."
      redirect_to players_path
    else
      render :edit
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    redirect_to players_path
  end

  private 

  def player_params
    params.require(:player).permit(:first_name, :last_name, :number, :position, :grad_year, :team_id)
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  layout "admin", except: [:files]
  before_action :set_resource, only: [:edit, :update, :destroy]

  def index
    @active_resources = Resource.where(active: true)
    @inactive_resources = Resource.where(active: false)
  end

  def files
    @resources = Resource.where(active: true)
  end

  def new
    @resource = Resource.new
  end

  def create
    @resource = Resource.new(resource_params)
    @resource.filename = params[:resource][:resource].original_filename

    uploaded_io = params[:resource][:resource]
    File.open(Rails.root.join('public', 'resources', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    
    if @resource.save
      flash[:notice] = "Resource uploaded"
      redirect_to resources_path
    else
      flash[:danger] = "There was an error"
      render :new
    end
  end

  def edit
  end

  def update
    if @resource.update(resource_params)
      flash[:notice] = "Resource updated"
      redirect_to resources_path
    else
      flash[:danger] = "There was an error"
      render :edit
    end
  end

  def destroy
    File.delete(Rails.root.join('public', 'resources', @resource.filename))
    flash[:notice] = "#{@resource.name} destroyed."
    @resource.destroy
    redirect_to resources_path
  end

  private

  def set_resource
    @resource = Resource.find(params[:id])
  end

  def resource_params
    params.require(:resource).permit(:name, :description, :active)
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def photos
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  layout "admin"

  def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)

    if @team.save
      flash[:notice] = "Team created"
      redirect_to teams_path
    else
      render :new
    end
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])

    if @team.update(team_params)
      flash[:notice] = "Team Updated"
      redirect_to teams_path
    else 
      render :edit   
    end   
  end

  def destroy
    @team = Team.find(params[:id])
    @team.players.each do |player|
      player.team = nil
      player.save
    end
    @team.destroy
    redirect_to teams_path
  end

  private

  def team_params
    params.require(:team).permit(:name)
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  layout "admin", except: [:schedule]

  before_action :set_tournament, only: [:edit, :update, :show, :destroy]

  def index
    @tournaments = Tournament.all
  end

  def schedule
    @tournaments = Tournament.all.order("start_date ASC")
  end

  def show
  end

  def new
    @tournament = Tournament.new
  end

  def create
    @tournament = Tournament.new(tournament_params)

    if @tournament.save
      flash[:notice] = "The tournament was created"
      redirect_to tournaments_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @tournament.update(tournament_params)
      flash[:notice] = "Tournament updated"
      redirect_to tournaments_path
    else
      render :edit
    end
  end

  def destroy
    #TODO Make sure this works
    if !@tournament.games.nil?
      @tournament.games.each do |game|
        game.destroy
      end
    end
    @tournament.destroy
    redirect_to tournaments_path
  end

  private

  def set_tournament
    @tournament = Tournament.find(params[:id])
  end

  def tournament_params
    params.require(:tournament).permit(:name, :location, :start_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def format_date_t(date)
    date.strftime("%b %e, %Y")
  end

  def format_date_g(date)
    date.strftime("%b %e")
  end

  def format_time_g(time)
    time.strftime("%l:%M %P")
  end

end

app/views/coaches/_coach_form.html.erb
<%= render 'shared/form_errors', obj: @coach %>

<%= form_for @coach do |f| %>
  <div class='input-group'> 
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <br>
  <div class='input-group'>
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <br>
  <div class='input-group'>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <br>
  <div class='input-group'>
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <br>
  <div class='input-group'>
    <%= f.label :bio %>
    <%= f.text_area :bio, class: 'form-control' %>
  </div>
  <br>
  <div class='input-group'>
    <%= f.submit (@coach.new_record? ? 'Create Coach' : 'Edit Coach'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/coaches/coaching_staff.html.erb
<%= render 'shared/content_title', title: "Coaches" %>

<% @coaches.each do |coach| %>
  <div>
    <!-- <img style="float: left; margin-right: .7em; height:auto; width:auto; max-width:180px; max-height:180px;" src="" class="img-rounded"> -->
    <h3><%= "#{coach.first_name} #{coach.last_name}" %></h3>
    <h4><%= coach.title %></h4>
    <% if coach.email %>
      <h4><a href="mailto:<%= coach.email %>" target="_blank"><span class="glyphicon glyphicon-envelope"></span>Email</a></h5>
    <% end %>
    <p><%= coach.bio %></p>
    <br>
  </div>
<% end %>

app/views/coaches/edit.html.erb
<%= render 'shared/content_title', title: "Edit Coach: #{@coach.first_name} #{@coach.last_name}" %>

<%= render 'coach_form' %>

app/views/coaches/index.html.erb
<%= render 'shared/content_title', title: 'Coaches' %>

<h5><%= link_to 'New Coach', new_coach_path %></h5>
<table class="table">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Title</th>
    <th>Email</th>
    <th>Bio</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <% @coaches.each do |coach| %>
    <tr>
      <td><%= coach.first_name %></td>
      <td><%= coach.last_name %></td>
      <td><%= coach.title %></td>
      <td><%= coach.email %></td>
      <td><%= coach.bio %></td>
      <td><%= link_to 'Edit', edit_coach_path(coach) %></td>
      <td><%= link_to 'Delete', coach, confirm: "Are you sure you want to delete #{coach.first_name} #{coach.last_name}?", method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/coaches/new.html.erb
<%= render 'shared/content_title', title: 'New Coach' %>

<%= render 'coach_form' %>

app/views/games/_admin_game_list.html.erb
<% if !games.empty? %>
  <table class="table">
    <tr>
      <th>Tournament</th>
      <th>Date</th>
      <th>Time</th>
      <th>Team</th>
      <th>Opponent</th>
      <th>Pool</th>
      <th>H/A</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    <% games.each do |game| %>
      <tr>
        <td><%= game.tournament.name %></td>
        <td><%= game.date %></td>
        <td><%= game.time %></td>
        <td><%= game.team.name %></td>
        <td><%= game.opponent %></td>
        <td><%= game.pool %></td>
        <td><%= game.ha %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Delete', game, confirm: "Are you sure you want to delete this game?", method: :delete %></td>
      </td>
    <% end %>
  </table>
<% else %>
  <h5>There are no games.</h5>
<% end %>

app/views/games/_game_form.html.erb
<%= render 'shared/form_errors', obj: @game %>

<%= form_for @game do |f| %>
  <div class='input-group'>
    <%= f.label :tournament %>
    <%= f.collection_select :tournament_id, Tournament.all, :id, :name, class: 'form-control' %>
  </div>
  <br>
  <div class='input-group'>
    <%= f.label :pool %>
    <%= f.text_field :pool, class: 'form-control' %>
  </div>
  <br>
  <div class='input-group'>
    <%= f.label :team %>
    <%= f.collection_select :team_id, Team.all, :id, :name, class: 'form-control' %>
  </div>
  <br>
  <div class='input-group'>
    <%= f.label :opponent %>
    <%= f.text_field :opponent, class: 'form-control' %>
  </div>
  <br>
  <div class='input-group'>
    <%= f.label :home %>
    <%= f.check_box :home, class: 'form-control' %>
  </div>
  <br>
  <div class='input-group'>
    <%= f.label :date %>
    <%= f.date_field :date, class: 'form-control' %>
  </div>
  <br>
  <div class='input-group'>
    <%= f.label :time %>
    <%= f.time_field :time, class: 'form-control' %>
  </div>
  <br>
  <div class='input-group'>
    <%= f.submit (@game.new_record? ? 'Create Game' : 'Update Game'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/games/index.html.erb
<%= render 'shared/content_title', title: 'Games' %>

<h5><%= link_to 'New Game', new_game_path %></h5>


<%= render 'admin_game_list', games: @games %>

app/views/games/new.html.erb
<%= render 'shared/content_title', title: 'New Game' %>

<%= render 'game_form' %>

app/views/homes/index.html.erb
<!-- Facebook SDK -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script> 
<!-- End Facebook -->

<div class="jumbotron" style="background: url('images/jumbo.png')  no-repeat center; background-size: 100%;">
    <!-- <div class="jumbotron" style="background: url('{{ image.image_url }}') center no-repeat fixed;"> -->
  <div class="container">
    <div>
      <h1>Ashland Water Polo</h1>
      <p>Welcome to the home of the Grizzlies.</p>
    </div>
  </div>
</div>



<div class="row">
  <article class="col-md-8 col-md-offset-1 col-md-push-3">
    <h3 style="margin-top: 0px;">Welcome</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur iaculis leo ac porta feugiat. In ut dui vel dolor consequat ornare ut ut dolor. Aliquam erat volutpat. Mauris pretium rhoncus diam. Aenean pharetra libero et nibh condimentum, at molestie turpis laoreet. Nullam porttitor dui eget lorem pellentesque volutpat. Vestibulum a pretium eros. Vestibulum elementum hendrerit tempus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi rutrum turpis quis purus viverra, quis ultrices justo faucibus. Praesent quis libero a turpis posuere elementum et vel elit. Etiam interdum nec nunc sed porta. Praesent et nulla quis ligula volutpat facilisis in id neque. Curabitur fringilla est non placerat varius. Fusce semper nisi sit amet enim dignissim aliquet.</p>
    <p>Curabitur consectetur vestibulum tellus, ac vestibulum est blandit quis. Donec a leo suscipit, iaculis sem ac, consequat ante. Sed dictum elit eu eros feugiat vehicula. Maecenas laoreet rutrum facilisis. Cras posuere commodo nibh, ut scelerisque odio. Vivamus leo neque, fringilla ac tempus a, porttitor ut nisl. Donec nec elementum velit. Vestibulum malesuada metus eu fringilla posuere. Nam porta, magna sed luctus pharetra, risus enim convallis lacus, dignissim interdum magna urna et sapien. Praesent ac tristique turpis, id molestie ipsum. Duis in eleifend ipsum, at feugiat neque.</p>
    <br>
    <div class="visible-lg text-center">
      <iframe width="640" height="480" src="//www.youtube.com/embed/vxI43Q47dNg?rel=0" frameborder="0" allowfullscreen></iframe>
    </div>
    <div class="hidden-lg text-center">
      <iframe width="420" height="315" src="//www.youtube.com/embed/vxI43Q47dNg?rel=0" frameborder="0" allowfullscreen></iframe>
    </div>
  </article>
  <aside class="col-md-3 col-md-pull-9 text-center">
    <div class="fb-like-box" style="text-align: center;" data-href="https://www.facebook.com/AshlandWaterPolo" data-colorscheme="dark" data-show-faces="true" data-header="true" data-stream="true" data-show-border="false"></div>
  </aside>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="col-xs-12">
      <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
        <a class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    </div>
  <% end %>
<% end %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-colapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Ashland Water Polo', root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Roster', roster_path %></li>
        <li><%= link_to 'Coaches', coaching_staff_path %></li>
        <li><%= link_to 'Schedule', schedule_path %></li>
        <li><%= link_to 'Photos', photos_path %></li>
        <li><%= link_to 'Resources', files_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Polo</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= render 'shared/admin_nav' %>
    </div>

    <div class="container maincontent">
      <%= render 'layouts/messages' %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ashland Water Polo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/nav' %>

  <div class="container maincontent">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
</body>
</html>

app/views/players/_player_form.html.erb
<%= render 'shared/form_errors', obj: @player %>


<%= form_for @player do |f| %>
  <div class='input-group'>
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <br>
  <div class='input-group'>
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <br>
  <div class='input-group'>
    <%= f.label :team %>
    <%= f.collection_select :team_id, Team.all, :id, :name, class: 'form-control' %>
  </div>
  <br>
  <div class='input-group'>
    <%= f.label :number %>
    <%= f.number_field :number, class: 'form-control' %>
  </div>
  <br>
  <div class='input-group'>
    <%= f.label :position %>
    <%= f.text_field :position, class: 'form-control' %>
  </div>
  <br>
  <div class='input-group'>
    <%= f.label :grad_year %>
    <%= f.number_field :grad_year, class: 'form-control' %>
  </div>
  <br>
  <div class='input-group'>
    <%= f.submit (@player.new_record? ? 'Create Player' : 'Update Player'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/players/edit.html.erb
<%= render 'shared/content_title', title: "Edit Player: #{@player.first_name} #{@player.last_name}" %>

<%= render 'player_form' %>

app/views/players/index.html.erb
<%= render 'shared/content_title', title: 'Players List' %>

<%= link_to 'New Player', new_player_path %>

<% @teams.each do |team| %>
  <h3><%= link_to team.name, edit_team_path(team) %></h3>
  <% if team.players.empty? %>
    <h5>No players on this team.</h5>
  <% else %>
    <table class="table table-condensed"> 
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Number</th>
        <th>Position</th>
        <th>Grad Year</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
      <% team.players.each do |player| %>
        <tr>
          <td><%= player.first_name %></td>
          <td><%= player.last_name %></td>
          <td><%= player.number %></td>
          <td><%= player.position %></td>
          <td><%= player.grad_year %></td>
          <td><%= link_to 'Edit', edit_player_path(player) %></td>
          <td><%= link_to "Delete", player, confirm: "Are you sure?", method: :delete %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
<% end %>

<h3>Unassigned Players</h3>
<% if @unassigned_players.empty? %>
  <h5>No unassigned players</h5>
<% else %>
  <table border="1"> 
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Number</th>
      <th>Position</th>
      <th>Grad Year</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    <% @unassigned_players.each do |player| %>
      <tr>
        <td><%= player.first_name %></td>
        <td><%= player.last_name %></td>
        <td><%= player.number %></td>
        <td><%= player.position %></td>
        <td><%= player.grad_year %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to "delete", player, confirm: "Are you sure?", method: :delete %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/players/new.html.erb
<%= render 'shared/content_title', title: "New Player" %>

<%= render 'player_form' %>

app/views/players/roster.html.erb
<%= render 'shared/content_title', title: 'Roster' %>

<% @teams.each do |team| %>
  <h4><%= team.name %></h4>
  <% if !team.players.empty? %>
    <table class="table table-striped table-bordered table-condensed">
      <tr>
          <th class="col-xs-1">Number</th>
          <th class="col-xs-5">Name</th>
          <th class="col-xs-4">Position</th>
          <th class="col-xs-2">Grad Year</th>
      </tr>
      <% team.players.sort {|a,b| a.number <=> b.number}.each do |player| %>
        <tr>
          <td class="text-center"><%= player.number %></td>
          <td><%= "#{player.first_name} #{player.last_name}" %></td>
          <td><%= player.position %></td>
          <td><%= player.grad_year %></td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <h5>There are no players on this roster</h5>
  <% end %>
<% end %>

app/views/resources/_resource_form.html.erb
<%= render 'shared/form_errors', obj: @resource %>

<%= form_for @resource do |f| %>
  <div class="input-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <br>
  <% if @resource.new_record? %>
    <div class='input-group'>
      <%= f.label :resource %>
      <%= f.file_field :resource, class: 'btn btn-default btn-file' %>
    </div>
    <br>
  <% end %>
  <div class='input-group'>
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <br>
  <div class='input-group'>
    <%= f.label :active %>
    <%= f.check_box :active, class: 'checkbox' %>
  </div>
  <br>
  <div class='input-group'>
    <%= f.submit class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/resources/_resources_table.html.erb
<table class='table'>
  <tr>
    <th>Name</th>
    <th>Link</th>
    <th>Description</th>
    <th>Last Modified</th>
    <th>Edit Info</th>
    <th>Delete</th>
  </tr>
  <% resources.each do |resource| %>
  <tr>
    <td><%= resource.name %> </td>
    <td><%= link_to resource.filename, "/resources/#{resource.filename}" %> </td>
    <td><%= resource.description %> </td>
    <td><%= resource.updated_at %> </td>
    <td><%= link_to 'Edit Info', edit_resource_path(resource) %> </td>
    <td><%= link_to 'Delete', resource, confirm: "Are you sure you want to delete #{resource.name}", method: :delete %> </td>
  </tr>
  <% end %>
</table>

app/views/resources/edit.html.erb
<%= render 'shared/content_title', title: "Edit File: #{@resource.name}" %>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <div class="alert alert-info">
      <p>Please note you can only edit the file name and description. If you would like to change the actual file, please delete the current resource and start with a <%= link_to 'new resource', new_resource_path %>. </p>
    </div>
  </div>
</div>
<%= render 'resource_form' %>

app/views/resources/index.html.erb
<%= render 'shared/content_title', title: 'Resources' %>

<%= link_to 'New Resource', new_resource_path %>
<br><br>

<h4>Active Resources</h4>

<% if !@active_resources.empty? %>
  <%= render 'resources_table', resources: @active_resources %>
<% else %>
  <h5>There are no active resources.</h5>
<% end %>

<br>

<h4>Inactive Resources</h4>

<% if !@inactive_resources.empty? %>
  <%= render 'resources_table', resources: @inactive_resources %>
<% else %>
  <h5>There are no inactive resources.</h5>
<% end %>

app/views/resources/new.html.erb
<%= render 'shared/content_title', title: 'New Resource' %>

<%= render 'resource_form' %>

app/views/shared/_content_title.html.erb
<h2 class="lead">
  <%= title %>
  <!-- <hr> -->
</h2>

app/views/tournaments/edit.html.erb
<%= render 'shared/content_title', title: "Edit Tournament: #{@tournament.name}" %>

<%= render 'tournament_form' %>

app/views/tournaments/index.html.erb
<%= render 'shared/content_title', title: "Tournaments" %>

<%= link_to 'New Tournament', new_tournament_path %>
<br><br>

<% if !@tournaments.empty? %>
  <table class='table'>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    <% @tournaments.each do |tournament| %>
      <tr>
        <td><%= link_to tournament.name, tournament_path(tournament) %></td>
        <td><%= tournament.location %></td>
        <td><%= tournament.start_date %></td>
        <td><%= tournament.end_date %></td>
        <td><%= link_to 'Edit', edit_tournament_path(tournament) %></td>
        <td><%= link_to 'Delete', tournament, confirm: "Are you sure you want to delete #{tournament.name}?", method: :delete %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <h5>There are no tournaments added yet</h5>
<% end %>

app/views/tournaments/show.html.erb
<%= render 'shared/content_title', title: "Tournament: #{@tournament.name}" %>

<%= link_to 'Edit Tournament', edit_tournament_path(@tournament) %>

<dl class="dl-horizontal">
  <dt>Name: </dt>
  <dd><%= @tournament.name %></dd>
  <dt>Location: </dt>
  <dd><%= @tournament.location %></dd>
  <dt>Start Date: </dt>
  <dd><%= @tournament.start_date %></dd>
  <dt>End Date: </dt>
  <dd><%= @tournament.end_date %></dd>
</dl>

<h4>Games</h4>

<%= render 'games/admin_game_list', games: @tournament.games %>